[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
divvy = "HKbBGFwWNVYLa7MnyKVZoZNrVy9BthdizHXfKZNwGmZm"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
